services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "root@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  rent-cars-api:
    build: 
      context: .
      # To be used if there's any issue with ssl configuration.
      # dockerfile: Dockerfile.onlyhttp 
    environment:
      ConnectionStrings__sqlConnection: "Server=sqlserver,1433;Initial Catalog=RentCars;User ID=sa;Password=root@123;TrustServerCertificate=True"
      SECRETKEYJWT: ${JWT_SECRET_KEY}
      Kestrel__Certificates__Default__Path: /https/localhost.pfx
    ports:
      - "5000:5000"
      - 5002:5001
    volumes:
    # If using linux
      - ${HOME}/.aspnet/https/dotnet-devcert.pfx:/https/localhost.pfx
    # If using windows
    #  - ${USERPROFILE}/.aspnet/https:/https
  migrations:
    working_dir: "/app"
    build: 
      context: .
      dockerfile: Dockerfile.migrations
    command: sh -c "dotnet ef database update --project ./Api/Api.csproj --connection \"Server=sqlserver,1433;Initial Catalog=RentCars;User ID=sa;Password=root@123;TrustServerCertificate=True\""
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest 
    ports: 
      - 5200:8978

  
# "sqlConnection": "Server=localhost,1433;Initial Catalog=RentCars;User ID=sa;Password=root@123; TrustServerCertificate=True"