services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "root@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"


# "sqlConnection": "Server=localhost,1433;Initial Catalog=RentCars;User ID=sa;Password=root@123; TrustServerCertificate=True"